
/**
 * This file was generated by the JPA Modeler
 */
package entity;

import java.io.Serializable;

import javax.persistence.Basic;
import javax.persistence.Embeddable;

/**
 * @author Taleb
 */
@Embeddable
public class ExamenPreClinique implements Serializable {
    @Basic
    private String tension;
    @Basic
    private String poids;
    @Basic
    private String taille;
    @Basic
    private String glycemie;

    public String getGlycemie() {
        return this.glycemie;
    }

    public void setGlycemie(String glycemie) {
        this.glycemie = glycemie;
    }

    public String getPoids() {
        return this.poids;
    }

    public void setPoids(String poids) {
        this.poids = poids;
    }

    public String getTaille() {
        return this.taille;
    }

    public void setTaille(String taille) {
        this.taille = taille;
    }

    public String getTension() {
        return this.tension;
    }

    public void setTension(String tension) {
        this.tension = tension;
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
