/**
 * This file was generated by the JPA Modeler
 */
package entity;

import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.OneToOne;

/**
 * @author Taleb
 */
@Entity
public class Infermiere extends Personne implements Serializable {

    @OneToOne(targetEntity = Service.class)
    private Service service;

    public Service getService() {
        return this.service;
    }

    public void setService(Service service) {
        this.service = service;
    }

}
