/**
 * This file was generated by the JPA Modeler
 */
package entity;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Embeddable;

/**
 * @author Taleb
 */
@Embeddable
public class InfoCivil implements Serializable {

    @Basic
    private String profession;

    @Basic
    private String assurance;

    @Basic
    private String etatCivil;

    @Basic
    private String cdn;

    public InfoCivil() {
    }

    public InfoCivil(String profession, String assurance, String etatCivil, String cdn) {
        this.profession = profession;
        this.assurance = assurance;
        this.etatCivil = etatCivil;
        this.cdn = cdn;
    }

    @Override
    public String toString() {
        return "InfoCivil{" + "profession=" + profession + ", assurance=" + assurance + ", etatCivil=" + etatCivil + ", cdn=" + cdn + '}';
    }

    
    public boolean equals(InfoCivil o) {
        
        return this.toString().equals(o.toString());
    }

    
    
    public String getProfession() {
        return this.profession;
    }

    public void setProfession(String profession) {
        this.profession = profession;
    }

    public String getAssurance() {
        return this.assurance;
    }

    public void setAssurance(String assurance) {
        this.assurance = assurance;
    }

    public String getEtatCivil() {
        return this.etatCivil;
    }

    public void setEtatCivil(String etatCivil) {
        this.etatCivil = etatCivil;
    }

    public String getCdn() {
        return this.cdn;
    }

    public void setCdn(String cdn) {
        this.cdn = cdn;
    }

}
