/**
 * This file was generated by the JPA Modeler
 */
package entity;

import java.io.Serializable;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;

/**
 * @author Taleb
 */
@Entity
@NamedQueries({
        @NamedQuery(
                name = "Personne.findByUtilisateur",
                query = "SELECT p FROM Personne p WHERE p.utilisateur.id = :utilisateurID"
        ),
        }
        
)
public class Personne implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;


    @Embedded
    private InfoPersonnel infoPersonnel;

    @Embedded
    private InfoCivil infoCivil;

    @OneToOne(targetEntity = Utilisateur.class)
    private Utilisateur utilisateur;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public InfoPersonnel getInfoPersonnel() {
        return this.infoPersonnel;
    }

    public void setInfoPersonnel(InfoPersonnel infoPersonnel) {
        this.infoPersonnel = infoPersonnel;
    }

    public InfoCivil getInfoCivil() {
        return this.infoCivil;
    }

    public void setInfoCivil(InfoCivil infoCivil) {
        this.infoCivil = infoCivil;
    }

    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }

    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

}
