
/**
 * This file was generated by the JPA Modeler
 */
package entity;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.NamedQuery;

/**
 * @author Taleb
 */
@Entity
@NamedQuery(
    name  = "Secretaire.Connect",
    query = "SELECT s FROM Secretaire s "
            + " WHERE (s.utilisateur.email = :email OR s.utilisateur.username = :username)"
            + " AND s.utilisateur.password = :psw"
)
public class Secretaire extends Personne implements Serializable {}


//~ Formatted by Jindent --- http://www.jindent.com
